<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    
    <RuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('Windows')) AND $([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'x64'">win-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="$([MSBuild]::IsOSPlatform('Linux')) AND $([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'x64'">linux-x64</RuntimeIdentifier>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <IsRelease></IsRelease>
    <Profile>debug</Profile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <IsRelease>--release</IsRelease>
    <Profile>release</Profile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
    <NativeTarget>x86_64-pc-windows-msvc</NativeTarget>
    <LibName>kira_ffi.dll</LibName>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
    <NativeTarget>x86_64-unknown-linux-gnu</NativeTarget>
    <LibName>libkira_ffi.so</LibName>    
  </PropertyGroup>

  <Target Name="BuildNative" BeforeTargets="BeforeBuild">
    <Exec Command="cargo build $(IsRelease) --target $(NativeTarget)" WorkingDirectory="../kira_ffi" EnvironmentVariables="CARGO_TARGET_DIR=../kira_ffi/target" />
  </Target>

  <ItemGroup>
    <Content Include="build/KiraSharp.targets" Pack="true" PackagePath="build/" />
    <Content Include="../kira_ffi/target/$(NativeTarget)/$(Profile)/$(LibName)">
      <Pack>true</Pack>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackagePath>runtimes/$(RuntimeIdentifier)/native/$(LibName)</PackagePath>
      <Link>$(LibName)</Link>
    </Content>
  </ItemGroup>

</Project>
