<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    
    <RuntimeIdentifiers Condition="$([MSBuild]::IsOSPlatform('Windows')) AND $([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'x64'">win-x64</RuntimeIdentifiers>
    <RuntimeIdentifiers Condition="$([MSBuild]::IsOSPlatform('Linux')) AND $([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture) == 'x64'">linux-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <PropertyGroup>
    <IsRelease Condition="'$(Configuration)'=='Debug'"></IsRelease>
    <IsRelease Condition="'$(Configuration)'=='Release'">--release</IsRelease>
    
    <NativeTarget Condition="'$(RuntimeIdentifiers)' == 'win-x64'">x86_64-pc-windows-msvc</NativeTarget>
    <NativeTarget Condition="'$(RuntimeIdentifiers)' == 'linux-x64'">x86_64-unknown-linux-gnu</NativeTarget>
    
    <Profile Condition="'$(Configuration)'=='Debug'">debug</Profile>
    <Profile Condition="'$(Configuration)'=='Release'">release</Profile>
  </PropertyGroup>

  <Target Name="BuildNative" BeforeTargets="BeforeBuild">
    <Exec Command="cargo build $(IsRelease) --target $(NativeTarget)" WorkingDirectory="../kira_ffi" />

    <ItemGroup>
      <None Include="../kira_ffi/target/$(NativeTarget)/$(Profile)/kira_ffi.dll" Condition="'$(RuntimeIdentifiers)' == 'win-x64'">
        <Pack>true</Pack>
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        <PackagePath>runtimes/win-x64/native/kira_ffi.dll</PackagePath>
        <Link>kira_ffi.dll</Link>
      </None>
      <None Include="../kira_ffi/target/$(NativeTarget)/$(Profile)/libkira_ffi.so" Condition="'$(RuntimeIdentifiers)' == 'linux-x64'">
        <Pack>true</Pack>
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        <PackagePath>runtimes/win-x64/native/libkira_ffi.so</PackagePath>
        <Link>libkira_ffi.so</Link>
      </None>
    </ItemGroup>
  </Target>

</Project>
